'use client'

export {
  RiLoginBoxLine,
  RiEyeOffLine,
  RiEyeLine,
  RiMenuLine,
  RiNotificationLine,
  RiTeamFill,
  RiTeamLine,
  RiBriefcaseFill,
  RiHammerFill,
  RiHammerLine,
  RiBuilding3Fill,
  RiBuilding3Line,
  RiFile2Fill,
  RiFile2Line,
  RiUserSettingsLine,
  RiLogoutCircleLine,
  RiDeleteBinLine,
  RiSearchLine,
  RiHome8Line,
  RiParentLine,
  RiCopyrightLine,
  RiCompasses2Line,
  RiAddLine,
  RiEdit2Line,
  RiDeleteBackLine,
  RiUser2Fill,
  RiShieldStarFill,
  RiRefreshLine,
  RiArrowLeftLine,
  RiErrorWarningLine,
  RiDoorLockLine,
  RiMailLine,
  RiMoneyDollarCircleLine,
  RiProfileLine,
} from 'react-icons/ri'

export { FcStatistics, FcBusinessman, FcSalesPerformance } from 'react-icons/fc'
